### ISSUE TITLE
Crash when XDG basedir envs are set

### ISSUE THREAD

**Issue by psnszsn** [nwg-piotr/sway-gtk-menu#12]
The program crashes when either of `XDG_CONFIG_HOME` or `XDG_CACHE_HOME` is set. 
```
Traceback (most recent call last):
  File "menu.py", line 74, in <module>
    config_dir = config_dirs()[0]
  File "/usr/lib/python3.8/site-packages/sgtk-menu/tools.py", line 90, in config_dirs
    paths.append(os.path.join(os.environ("XDG_CONFIG_HOME"), 'sgtk-menu'))
TypeError: '_Environ' object is not callable
```

**Comment by nwg-piotr** [comment]
Very true. Fix on the way.

**Comment by nwg-piotr** [comment]
I'm having trouble defining XDG dirs on Arch / Wayland, but theoretically it should be OK now. Could you take a look?

**Comment by psnszsn** [comment]
That fixed it. Thank you!

**Comment by nwg-piotr** [comment]
Thank you, too!
